namespace TownOfUsReworked.Patches
{
    internal enum RPC
    {
        PlayAnimation,
        CompleteTask,
        SyncSettings,
        SetRole,
        Exiled,
        CheckName,
        SetName,
        CheckColor,
        SetColor,
        SetHat,
        SetSkin,
        ReportDeadBody,
        MurderPlayer,
        SendChat,
        StartMeeting,
        SetScanner,
        SendChatNote,
        SetPet,
        SetStartCounter,
        EnterVent,
        ExitVent,
        SnapTo,
        Close,
        BBFDNCCEJHI,
        CastVote,
        ClearVote,
        AddVote,
        CloseDoorsOfType,
        RepairSystem,
        SetTasks,
        UpdateGameData
    }
}