namespace TownOfUsReworked.Enums
{
    public enum WinLoseRPC
    {
        AmnesiacLose,
        GlitchWin,
        GlitchLose,
        JuggernautWin,
        JuggernautLose,
        ArsonistWin,
        ArsonistLose,
        JesterWin,
        JesterLose,
        ExecutionerWin,
        ExecutionerLose,
        SurvivorWin,
        SurvivorLose,
        PlaguebearerWin,
        PlaguebearerLose,
        PestilenceWin,
        PestilenceLose,
        WerewolfWin,
        WerewolfLose,
        CannibalWin,
        CannibalLose,
        MurdererWin,
        MurdererLose,
        SerialKillerWin,
        SerialKillerLose,
        CryomaniacWin,
        CryomaniacLose,
        TrollWin,
        TrollLose,
        ThiefLose,
        PirateWin,
        PirateLose,
        PhantomWin,
        PhantomLose,
        GuardianAngelWin,
        GuardianAngelLose,

        CrewWin,
        CrewLose,
        IntruderWin,
        IntruderLose,
        SyndicateWin,
        SyndicateLose,
        AllNeutralsWin,

        UndeadWin,
        UndeadLose,
        CabalWin,
        CabalLose,
        SectWin,
        SectLose,
        ReanimatedWin,
        ReanimatedLose,

        AllNKsWin,

        LoveWin,
        TaskmasterWin,
        RivalWin,
        CorruptedLose,
        CorruptedWin,
        OverlordWin,

        NobodyWins,
    }
}