namespace TownOfUs
{
    public enum Alignment
    {
        CrewSupport,
        CrewInvest,
        CrewProt,
        CrewKill,
        CrewUtil,
        CrewSov,
        CrewCheck,
        PostmortalCrew,
        IntruderSupport,
        IntruderConceal,
        IntruderDecep,
        IntruderKill,
        IntruderUtil,
        PostmortalIntruder,
        NeutralKill,
        NeutralChaos,
        NeutralEvil,
        NeutralBen,
        NeutralPower,
        PostmortalNeutral,
        SyndicateKill,
        SyndicateSupport,
        SyndicatePower,
        SyndicateUtil,
        PostmortalSyndicate,
        Coven,
        AgentBase,
        AgentArmageddon,
        Daybreakers
    }
}
