using TownOfUs.CrewmateRoles.EngineerMod;
using TownOfUs.CrewmateRoles.SheriffMod;
using TownOfUs.CrewmateRoles.MedicMod;
using TownOfUs.CustomOption;
using TownOfUs.NeutralRoles.ExecutionerMod;
using TownOfUs.CrewmateRoles.HaunterMod;
using TownOfUs.CrewmateRoles.MediumMod;
using TownOfUs.NeutralRoles.GuardianAngelMod;
using TownOfUs.CrewmateRoles.ShifterMod;
using TownOfUs.ImpostorRoles.ConsigliereMod;

namespace TownOfUs
{
    public enum WhoCanVentOptions
    {
        Default,
        Everyone,
        Noone
    }
    
    public enum DisableSkipButtonMeetings
    {
        No,
        Emergency,
        Always
    }

    public enum GameMode
    {
        Classic,
        AllAny,
        KillingOnly,
        //Mafia,
        Custom
    }

    public static class CustomGameOptions
    {
        public static WhoCanVentOptions WhoCanVent => (WhoCanVentOptions)Generate.WhoCanVent.Get();
        public static int MayorOn => (int)Generate.MayorOn.Get();
        public static int JesterOn => (int)Generate.JesterOn.Get();
        public static int SheriffOn => (int)Generate.SheriffOn.Get();
        public static int JanitorOn => (int)Generate.JanitorOn.Get();
        public static int EngineerOn => (int)Generate.EngineerOn.Get();
        public static int SwapperOn => (int)Generate.SwapperOn.Get();
        public static int ShifterOn => (int)Generate.ShifterOn.Get();
        public static int AmnesiacOn => (int)Generate.AmnesiacOn.Get();
        public static int InvestigatorOn => (int)Generate.InvestigatorOn.Get();
        public static int TimeLordOn => (int)Generate.TimeLordOn.Get();
        public static int MedicOn => (int)Generate.MedicOn.Get();
        public static int GlitchOn => (int)Generate.GlitchOn.Get();
        public static int MorphlingOn => (int)Generate.MorphlingOn.Get();
        public static int ExecutionerOn => (int)Generate.ExecutionerOn.Get();
        public static int AgentOn => (int)Generate.AgentOn.Get();
        public static int SnitchOn => (int)Generate.SnitchOn.Get();
        public static int MinerOn => (int)Generate.MinerOn.Get();
        public static int WraithOn => (int)Generate.WraithOn.Get();
        public static int ArsonistOn => (int)Generate.ArsonistOn.Get();
        public static int AltruistOn => (int)Generate.AltruistOn.Get();
        public static int UndertakerOn => (int)Generate.UndertakerOn.Get();
        public static int UnderdogOn => (int)Generate.UnderdogOn.Get();
        public static int PhantomOn => (int)Generate.PhantomOn.Get();
        public static int VigilanteOn => (int)Generate.VigilanteOn.Get();
        public static int HaunterOn => (int)Generate.HaunterOn.Get();
        public static int GrenadierOn => (int)Generate.GrenadierOn.Get();
        public static int VeteranOn => (int)Generate.VeteranOn.Get();
        public static int TrackerOn => (int)Generate.TrackerOn.Get();
        public static int OperativeOn => (int)Generate.OperativeOn.Get();
        public static int PoisonerOn => (int)Generate.PoisonerOn.Get();
        public static int TraitorOn => (int)Generate.TraitorOn.Get();
        public static int TransporterOn => (int)Generate.TransporterOn.Get();
        public static int MediumOn => (int)Generate.MediumOn.Get();
        public static int SurvivorOn => (int)Generate.SurvivorOn.Get();
        public static int GuardianAngelOn => (int)Generate.GuardianAngelOn.Get();
        public static int MysticOn => (int)Generate.MysticOn.Get();
        public static int BlackmailerOn => (int)Generate.BlackmailerOn.Get();
        public static int PlaguebearerOn => (int)Generate.PlaguebearerOn.Get();
        public static int JuggernautOn => (int)Generate.JuggernautOn.Get();
        public static int WerewolfOn => (int)Generate.WerewolfOn.Get();
        public static int DetectiveOn => (int)Generate.DetectiveOn.Get();
        public static int CamouflagerOn => (int)Generate.CamouflagerOn.Get();
        public static int TaskmasterOn => (int)Generate.TaskmasterOn.Get();
        public static int DisguiserOn => (int) Generate.DisguiserOn.Get();
        public static int CannibalOn => (int) Generate.CannibalOn.Get();
        public static int TorchOn => (int)Generate.TorchOn.Get();
        public static int LighterOn => (int)Generate.LighterOn.Get();
        public static int DiseasedOn => (int)Generate.DiseasedOn.Get();
        public static int TiebreakerOn => (int)Generate.TiebreakerOn.Get();
        public static int GiantOn => (int)Generate.GiantOn.Get();
        public static int DwarfOn => (int)Generate.DwarfOn.Get();
        public static int ButtonBarryOn => (int)Generate.ButtonBarryOn.Get();
        public static int BaitOn => (int)Generate.BaitOn.Get();
        public static int LoversOn => (int)Generate.LoversOn.Get();
        public static int ConsigliereOn => (int)Generate.ConsigliereOn.Get();
        public static int CowardOn => (int)Generate.CowardOn.Get();
        public static int DrunkOn => (int)Generate.DrunkOn.Get();
        public static int DraculaOn => (int)Generate.DraculaOn.Get();
        public static int VolatileOn => (int) Generate.VolatileOn.Get();
        public static float InitialCooldowns => Generate.InitialCooldowns.Get();
        public static bool BothLoversDie => Generate.BothLoversDie.Get();
        public static bool VigiKillOther => Generate.VigiKillOther.Get();
        public static bool VigiKillsJester => Generate.VigiKillsJester.Get();
        public static bool VigiKillsExecutioner => Generate.VigiKillsExecutioner.Get();
        public static float VigiKillCd => Generate.VigiKillCd.Get();
        public static float JanitorCleanCd => Generate.JanitorCleanCd.Get();
        public static int MayorVoteBank => (int)Generate.MayorVoteBank.Get();
        public static bool MayorAnonymous => Generate.MayorAnonymous.Get();
        public static bool SwapperButton => Generate.SwapperButton.Get();
        public static float ShifterCd => Generate.ShifterCd.Get();
        public static BecomeEnum ShiftedBecomes => (BecomeEnum)Generate.ShiftedBecomes.Get();
        public static float SheriffAccuracy => Generate.SheriffAccuracy.Get();
        public static InterrogatePer SheriffFixPer => (InterrogatePer)Generate.InterrogatePer.Get();
        public static bool SFXOn => Generate.SFXOn.Get();
        public static float FootprintSize => Generate.FootprintSize.Get();
        public static float FootprintInterval => Generate.FootprintInterval.Get();
        public static float FootprintDuration => Generate.FootprintDuration.Get();
        public static bool AnonymousFootPrint => Generate.AnonymousFootPrint.Get();
        public static bool VentFootprintVisible => Generate.VentFootprintVisible.Get();
        public static bool JesterButton => Generate.JesterButton.Get();
        public static bool JesterVent => Generate.JesterVent.Get();
        public static bool ExeVent => Generate.ExeVent.Get();
        public static bool RewindRevive => Generate.RewindRevive.Get();
        public static float RewindDuration => Generate.RewindDuration.Get();
        public static float RewindCooldown => Generate.RewindCooldown.Get();
        public static int RewindMaxUses => (int)Generate.RewindMaxUses.Get();
        public static ShieldOptions ShowShielded => (ShieldOptions)Generate.ShowShielded.Get();
        public static NotificationOptions NotificationShield => (NotificationOptions)Generate.WhoGetsNotification.Get();
        public static bool ShieldBreaks => Generate.ShieldBreaks.Get();
        public static float MedicReportNameDuration => Generate.MedicReportNameDuration.Get();
        public static float MedicReportColorDuration => Generate.MedicReportColorDuration.Get();
        public static bool ShowReports => Generate.MedicReportSwitch.Get();
        public static float InterrogateCd => Generate.InterrogateCooldown.Get();
        public static bool NeutEvilRed => Generate.NeutEvilRed.Get();
        public static bool NeutKillingRed => Generate.NeutKillingRed.Get();
        public static bool TraitorColourSwap => Generate.TraitorColourSwap.Get();
        public static float MimicCooldown => Generate.MimicCooldownOption.Get();
        public static float MimicDuration => Generate.MimicDurationOption.Get();
        public static float HackCooldown => Generate.HackCooldownOption.Get();
        public static float HackDuration => Generate.HackDurationOption.Get();
        public static float GlitchKillCooldown => Generate.GlitchKillCooldownOption.Get();
        public static int GlitchHackDistance => Generate.GlitchHackDistanceOption.Get();
        public static bool GlitchVent => Generate.GlitchVent.Get();
        public static float JuggKillCooldown => Generate.GlitchKillCooldownOption.Get();
        public static float MorphlingCd => Generate.MorphlingCooldown.Get();
        public static float MorphlingDuration => Generate.MorphlingDuration.Get();
        public static bool MorphlingVent => Generate.MorphlingVent.Get();
        public static float CamouflagerCd => Generate.CamouflagerCooldown.Get();
        public static float CamouflagerDuration => Generate.CamouflagerDuration.Get();
        public static bool ColourblindComms => Generate.ColourblindComms.Get();
        public static bool MeetingColourblind => Generate.MeetingColourblind.Get();
        public static OnTargetDead OnTargetDead => (OnTargetDead)Generate.OnTargetDead.Get();
        public static bool ExecutionerButton => Generate.ExecutionerButton.Get();
        public static bool SnitchSeesNeutrals => Generate.SnitchSeesNeutrals.Get();
        public static bool SnitchSeesCrew => Generate.SnitchSeesCrew.Get();
        public static bool SnitchSeesRoles => Generate.SnitchSeesRoles.Get();
        public static int SnitchTasksRemaining => (int)Generate.SnitchTasksRemaining.Get();
        public static bool SnitchSeesImpInMeeting => Generate.SnitchSeesImpInMeeting.Get();
        public static bool SnitchSeesTraitor => Generate.SnitchSeesTraitor.Get();
        public static float MineCd => Generate.MineCooldown.Get();
        public static float InvisCd => Generate.InvisCooldown.Get();
        public static float InvisDuration => Generate.InvisDuration.Get();
        public static bool WraithVent => Generate.WraithVent.Get();
        public static bool ImpostorSeeRoles => Generate.ImpostorSeeRoles.Get();
        public static bool DeadSeeRoles => Generate.DeadSeeRoles.Get();
        public static bool DisableLevels => Generate.DisableLevels.Get();
        public static bool WhiteNameplates => Generate.WhiteNameplates.Get();
        public static bool CustomCrewColors => Generate.CustomCrewColors.Get();
        public static bool CustomImpColors => Generate.CustomImpColors.Get();
        public static bool CustomNeutColors => Generate.CustomNeutColors.Get();
        public static bool CustomModifierColors => Generate.CustomModifierColors.Get();
        public static bool CustomObjectifierColors => Generate.CustomObjectifierColors.Get();
        public static bool SeeTasksDuringRound => Generate.SeeTasksDuringRound.Get();
        public static bool SeeTasksDuringMeeting => Generate.SeeTasksDuringMeeting.Get();
        public static bool SeeTasksWhenDead => Generate.SeeTasksWhenDead.Get();
        public static float DouseCd => Generate.DouseCooldown.Get();
        public static float IgniteCd => Generate.IgniteCooldown.Get();
        public static int MaxDoused => (int)Generate.MaxDoused.Get();
        public static int MinNeutralNonKillingRoles => (int)Generate.MinNeutralNonKillingRoles.Get();
        public static int MaxNeutralNonKillingRoles => (int)Generate.MaxNeutralNonKillingRoles.Get();
        public static int MinNeutralKillingRoles => (int)Generate.MinNeutralKillingRoles.Get();
        public static int MaxNeutralKillingRoles => (int)Generate.MaxNeutralKillingRoles.Get();
        public static bool RandomNumberImps => Generate.RandomNumberImps.Get();
        public static int NeutralRoles => (int)Generate.NeutralRoles.Get();
        public static bool AddArsonist => Generate.AddArsonist.Get();
        public static bool AddPlaguebearer => Generate.AddPlaguebearer.Get();
        public static bool ParallelMedScans => Generate.ParallelMedScans.Get();
        public static EngineerFixPer EngineerFixPer => (EngineerFixPer)Generate.EngineerPer.Get();
        public static float ReviveDuration => Generate.ReviveDuration.Get();
        public static bool AltruistTargetBody => Generate.AltruistTargetBody.Get();
        public static float DragCd => Generate.DragCooldown.Get();
        public static bool UndertakerVent => Generate.UndertakerVent.Get();
        public static bool UndertakerVentWithBody => Generate.UndertakerVentWithBody.Get();
        public static bool AssassinGuessNeutralBenign => Generate.AssassinGuessNeutralBenign.Get();
        public static bool AssassinGuessNeutralEvil => Generate.AssassinGuessNeutralEvil.Get();
        public static bool AssassinGuessPest => Generate.AssassinGuessPest.Get();
        public static bool AssassinGuessModifiers => Generate.AssassinGuessModifiers.Get();
        public static bool AssassinGuessLovers => Generate.AssassinGuessLovers.Get();
        public static int AssassinKills => (int)Generate.AssassinKills.Get();
        public static int NumberOfImpostorAssassins => (int)Generate.NumberOfImpostorAssassins.Get();
        public static int NumberOfCrewAssassins => (int)Generate.NumberOfCrewAssassins.Get();
        public static int NumberOfNeutralAssassins => (int)Generate.NumberOfNeutralAssassins.Get();
        public static bool AmneTurnImpAssassin => Generate.AmneTurnImpAssassin.Get();
        public static bool AmneTurnCrewAssassin => Generate.AmneTurnCrewAssassin.Get();
        public static bool AmneTurnNeutAssassin => Generate.AmneTurnNeutAssassin.Get();
        public static bool TraitorCanAssassin => Generate.TraitorCanAssassin.Get();
        public static bool AssassinMultiKill => Generate.AssassinMultiKill.Get();
        public static bool AssassinSnitchViaCrewmate => Generate.AssassinSnitchViaCrewmate.Get();
        public static bool AssassinateAfterVoting => Generate.AssassinateAfterVoting.Get();
        public static float UnderdogKillBonus => Generate.UnderdogKillBonus.Get();
        public static float JuggKillBonus => Generate.JuggKillBonus.Get();
        public static bool UnderdogIncreasedKC => Generate.UnderdogIncreasedKC.Get();
        public static int PhantomTasksRemaining => (int)Generate.PhantomTasksRemaining.Get();
        public static int HaunterTasksRemainingClicked => (int)Generate.HaunterTasksRemainingClicked.Get();
        public static int HaunterTasksRemainingAlert => (int)Generate.HaunterTasksRemainingAlert.Get();
        public static bool HaunterRevealsNeutrals => Generate.HaunterRevealsNeutrals.Get();
        public static bool HaunterRevealsCrew => Generate.HaunterRevealsCrew.Get();
        public static bool HaunterRevealsTraitor => Generate.HaunterRevealsTraitor.Get();
        public static bool HaunterRevealsRoles => Generate.HaunterRevealsRoles.Get();
        public static HaunterCanBeClickedBy HaunterCanBeClickedBy => (HaunterCanBeClickedBy)Generate.HaunterCanBeClickedBy.Get();
        public static float GrenadeCd => Generate.GrenadeCooldown.Get();
        public static float GrenadeDuration => Generate.GrenadeDuration.Get();
        public static bool GrenadierIndicators => Generate.GrenadierIndicators.Get();
        public static bool GrenadierVent => Generate.GrenadierVent.Get();
        public static float FlashRadius => Generate.FlashRadius.Get();
        public static float AlertCd => Generate.AlertCooldown.Get();
        public static float AlertDuration => Generate.AlertDuration.Get();
        public static int MaxAlerts => (int)Generate.MaxAlerts.Get();
        public static float UpdateInterval => Generate.UpdateInterval.Get();
        public static float TrackCd => Generate.TrackCooldown.Get();
        public static bool ResetOnNewRound => Generate.ResetOnNewRound.Get();
        public static int MaxTracks => (int)Generate.MaxTracks.Get();
        public static float PoisonCd => Generate.PoisonCooldown.Get();
        public static float PoisonDuration => Generate.PoisonDuration.Get();
        public static bool PoisonerVent => Generate.PoisonerVent.Get();
        public static int LatestSpawn => (int)Generate.LatestSpawn.Get();
        public static bool NeutralKillingStopsTraitor => Generate.NeutralKillingStopsTraitor.Get();
        public static float TransportCooldown => Generate.TransportCooldown.Get();
        public static int TransportMaxUses => (int)Generate.TransportMaxUses.Get();
        public static bool RememberArrows => Generate.RememberArrows.Get();
        public static float RememberArrowDelay => Generate.RememberArrowDelay.Get();
        public static float MediateCooldown => Generate.MediateCooldown.Get();
        public static bool ShowMediatePlayer => Generate.ShowMediatePlayer.Get();
        public static bool ShowMediumToDead => Generate.ShowMediumToDead.Get();
        public static DeadRevealed DeadRevealed => (DeadRevealed)Generate.DeadRevealed.Get();
        public static float VestCd => Generate.VestCd.Get();
        public static float VestDuration => Generate.VestDuration.Get();
        public static float VestKCReset => Generate.VestKCReset.Get();
        public static int MaxVests => (int)Generate.MaxVests.Get();
        public static float ProtectCd => Generate.ProtectCd.Get();
        public static float ProtectDuration => Generate.ProtectDuration.Get();
        public static float ProtectKCReset => Generate.ProtectKCReset.Get();
        public static int MaxProtects => (int)Generate.MaxProtects.Get();
        public static ProtectOptions ShowProtect => (ProtectOptions)Generate.ShowProtect.Get();
        public static BecomeOptions GaOnTargetDeath => (BecomeOptions)Generate.GaOnTargetDeath.Get();
        public static bool GATargetKnows => Generate.GATargetKnows.Get();
        public static bool GAKnowsTargetRole => Generate.GAKnowsTargetRole.Get();
        public static bool ExeTargetKnows => Generate.ExeTargetKnows.Get();
        public static bool ExeKnowsTargetRole => Generate.ExeKnowsTargetRole.Get();
        public static float MysticArrowDuration => Generate.MysticArrowDuration.Get();
        public static float BlackmailCd => Generate.BlackmailCooldown.Get();
        public static float GiantSpeed => Generate.GiantSpeed.Get();
        public static float GiantScale => Generate.GiantScale.Get();
        public static float DwarfSpeed => Generate.DwarfSpeed.Get();
        public static float DwarfScale => Generate.DwarfScale.Get();
        public static float DiseasedMultiplier => Generate.DiseasedKillMultiplier.Get();
        public static float BaitMinDelay => Generate.BaitMinDelay.Get();
        public static float BaitMaxDelay => Generate.BaitMaxDelay.Get();
        public static float InfectCd => Generate.InfectCooldown.Get();
        public static float PestKillCd => Generate.PestKillCooldown.Get();
        public static bool PestVent => Generate.PestVent.Get();
        public static float RampageCd => Generate.RampageCooldown.Get();
        public static float RampageDuration => Generate.RampageDuration.Get();
        public static float RampageKillCd => Generate.RampageKillCooldown.Get();
        public static bool WerewolfVent => Generate.WerewolfVent.Get();
        public static float BugCooldown => Generate.BugCooldown.Get();
        public static bool BugsRemoveOnNewRound => Generate.BugsRemoveOnNewRound.Get();
        public static int MaxBugs => (int)Generate.MaxBugs.Get();
        public static float MinAmountOfTimeInBug => Generate.MinAmountOfTimeInBug.Get();
        public static float BugRange => Generate.BugRange.Get();
        public static float MinAmountOfPlayersInBug => Generate.MinAmountOfPlayersInBug.Get();
        public static float InitialExamineCd => Generate.InitialExamineCooldown.Get();
        public static float ExamineCd => Generate.ExamineCooldown.Get();
        public static float RecentKill => Generate.RecentKill.Get();
        public static bool DetectiveReportOn => Generate.DetectiveReportOn.Get();
        public static float DetectiveRoleDuration => Generate.DetectiveRoleDuration.Get();
        public static float DetectiveFactionDuration => Generate.DetectiveFactionDuration.Get();
        public static bool VentImprovements => Generate.VentImprovements.Get();
        public static bool VitalsLab => Generate.VitalsLab.Get();
        public static bool ColdTempDeathValley => Generate.ColdTempDeathValley.Get();
        public static bool WifiChartCourseSwap => Generate.WifiChartCourseSwap.Get();
        public static bool RandomMapEnabled => Generate.RandomMapEnabled.Get();
        public static float RandomMapSkeld => Generate.RandomMapSkeld.Get();
        public static float RandomMapMira => Generate.RandomMapMira.Get();
        public static float RandomMapPolus => Generate.RandomMapPolus.Get();
        public static float RandomMapAirship => Generate.RandomMapAirship.Get();
        public static float RandomMapSubmerged => Patches.SubmergedCompatibility.Loaded ? Generate.RandomMapSubmerged.Get() : 0f;
        public static bool AutoAdjustSettings => Generate.AutoAdjustSettings.Get();
        public static bool SmallMapHalfVision => Generate.SmallMapHalfVision.Get();
        public static float SmallMapDecreasedCooldown => Generate.SmallMapDecreasedCooldown.Get();
        public static float LargeMapIncreasedCooldown => Generate.LargeMapIncreasedCooldown.Get();
        public static int SmallMapIncreasedShortTasks => (int)Generate.SmallMapIncreasedShortTasks.Get();
        public static int SmallMapIncreasedLongTasks => (int)Generate.SmallMapIncreasedLongTasks.Get();
        public static int LargeMapDecreasedShortTasks => (int)Generate.LargeMapDecreasedShortTasks.Get();
        public static int LargeMapDecreasedLongTasks => (int)Generate.LargeMapDecreasedLongTasks.Get();
        public static bool JuggVent => Generate.JuggVent.Get();
        public static bool ArsoVent => Generate.ArsoVent.Get();
        public static bool PBVent => Generate.PBVent.Get();
        public static DisableSkipButtonMeetings SkipButtonDisable => (DisableSkipButtonMeetings)Generate.SkipButtonDisable.Get();
        public static GameMode GameMode => (GameMode)Generate.GameMode.Get();
        public static float DisguiseCooldown => Generate.DisguiseCooldown.Get();
        public static float TimeToDisguise => Generate.TimeToDisguise.Get();
        public static float DisguiseDuration => Generate.DisguiseDuration.Get();
        public static bool VigiKillsCannibal => Generate.VigiKillsCannibal.Get();
        public static float CannibalCd => Generate.CannibalCd.Get();
        public static int CannibalBodyCount => (int)Generate.CannibalBodyCount.Get();
        public static bool CannibalVent => Generate.CannibalVent.Get();
        public static bool CrewMustDie => Generate.CrewMustDie.Get();
        public static int TMOn => (int)Generate.TMOn.Get();
        public static float FreezeDuration => Generate.FreezeDuration.Get();
        public static float FreezeCooldown => Generate.FreezerCooldown.Get();
        public static int MayorCount => (int)Generate.MayorCount.Get();
        public static int DetectiveCount => (int)Generate.DetectiveCount.Get();
        public static int InvestigatorCount => (int)Generate.DetectiveCount.Get();
        public static int MediumCount => (int)Generate.MediumCount.Get();
        public static int MysticCount => (int)Generate.MysticCount.Get();
        public static int SheriffCount => (int)Generate.SheriffCount.Get();
        public static int SnitchCount => (int)Generate.SnitchCount.Get();
        public static int AgentCount => (int)Generate.AgentCount.Get();
        public static int TrackerCount => (int)Generate.TrackerCount.Get();
        public static int OperativeCount => (int)Generate.OperativeCount.Get();
        public static int VeteranCount => (int)Generate.VeteranCount.Get();
        public static int VigilanteCount => (int)Generate.VigilanteCount.Get();
        public static int MedicCount => (int)Generate.MedicCount.Get();
        public static int AltruistCount => (int)Generate.AltruistCount.Get();
        public static int EngineerCount => (int)Generate.EngineerCount.Get();
        public static int ShifterCount => (int)Generate.ShifterCount.Get();
        public static int SwapperCount => (int)Generate.SwapperCount.Get();
        public static int TimeLordCount => (int)Generate.TimeLordCount.Get();
        public static int TransporterCount => (int)Generate.TransporterCount.Get();
        public static int AmnesiacCount => (int)Generate.AmnesiacCount.Get();
        public static int SurvivorCount => (int)Generate.SurvivorCount.Get();
        public static int GuardianAngelCount => (int)Generate.GuardianAngelCount.Get();
        public static int CannibalCount => (int)Generate.CannibalCount.Get();
        public static int ExecutionerCount => (int)Generate.ExecutionerCount.Get();
        public static int JesterCount => (int)Generate.JesterCount.Get();
        public static int ArsonistCount => (int)Generate.ArsonistCount.Get();
        public static int GlitchCount => (int)Generate.GlitchCount.Get();
        public static int JuggernautCount => (int)Generate.JuggernautCount.Get();
        public static int WerewolfCount => (int)Generate.WerewolfCount.Get();
        public static int PlaguebearerCount => (int)Generate.PlaguebearerCount.Get();
        public static int CamouflagerCount => (int)Generate.CamouflagerCount.Get();
        public static int GrenadierCount => (int)Generate.GrenadierCount.Get();
        public static int JanitorCount => (int)Generate.JanitorCount.Get();
        public static int UndertakerCount => (int)Generate.UndertakerCount.Get();
        public static int MorphlingCount => (int)Generate.MorphlingCount.Get();
        public static int PoisonerCount => (int)Generate.PoisonerCount.Get();
        public static int WraithCount => (int)Generate.WraithCount.Get();
        public static int UnderdogCount => (int)Generate.UnderdogCount.Get();
        public static int BlackmailerCount => (int)Generate.BlackmailerCount.Get();
        public static int MinerCount => (int)Generate.MinerCount.Get();
        public static int TimeMasterCount => (int)Generate.TMCount.Get();
        public static int DisguiserCount => (int)Generate.DisguiserCount.Get();
        public static bool MysticReportName => Generate.MysticReportName.Get();
        public static bool MysticReportRole => Generate.MysticReportRole.Get();
        public static float ConsigCd => Generate.RevealCooldown.Get();
        public static ConsigInfo ConsigInfo => (ConsigInfo)Generate.ConsigInfo.Get();
        public static int ConsigliereCount => (int)Generate.ConsigCount.Get();
        public static int DragModifier => (int)Generate.DragModifier.Get();
        public static int TMTasksRemaining => (int)Generate.TMTasksRemaining.Get();
        public static int TaskmasterCount => (int)Generate.TaskmasterCount.Get();
        public static bool TaskmasterVent => Generate.TaskmasterVent.Get();
        public static bool JestVentSwitch => Generate.JestSwitchVent.Get();
        public static bool ExeVentSwitch => Generate.ExeSwitchVent.Get();
        public static bool TLImmunity => Generate.TLImmunity.Get();
        public static int DraculaCount => (int)Generate.DraculaCount.Get();
        public static float BiteCd => Generate.BiteCooldown.Get();
        public static int AliveVampCount => (int)Generate.AliveVampCount.Get();
        public static bool DracVent => Generate.DracVent.Get();
        public static bool VampVent => Generate.VampVent.Get();
        public static bool DraculaConvertNeuts => Generate.DraculaConvertNeuts.Get();
    }
}