name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Test_Project_Path: TownOfUsReworked/TownOfUsReworked.csproj
      Root: TownOfUsReworked/

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Restore the application
      run: msbuild $env:Test_Project_Path /t:restore /p:Configuration=$env:Configuration

    - name: Publish the application
      run: msbuild $env:Test_Project_Path /t:publish /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
      
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Debug --no-restore

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: Reworked.dll
        path: TownOfUsReworked/bin/Debug/net6.0/Reworked.dll